### PR TITLE
Maybe cleaner code

### PR DESCRIPTION
**Pull request by Gamsti1337**
Some file had some ugly code and I changed it.

Didn't really change anything, just made the code more beautiful.

### CODE REVIEW

**Comment by seanjhardy** [comment]
Fix the GitHub code style errors (like semicolons) and I can approve

**Review by seanjhardy — CHANGES_REQUESTED** [review]
Fix the GitHub code style errors (like semicolons) and I can approve

**Comment by Gamsti1337** [comment]
What do you mean about "github code style errors".

**Comment by seanjhardy** [comment]
> What do you mean about "github code style errors".

this
image

**Comment by seanjhardy** [comment]
Also this branch has conflicts, could you resolve those?

**Comment by Gamsti1337** [comment]
I'm getting into those github errors, they seem easy.

From my knowledge I can't fix branch conflicts because I don't have write rights in this repo.

**Comment by Gamsti1337** [comment]
Also where can I see the github actions that says the problems

**Comment by Gamsti1337** [comment]
@seanjhardy they should be gone

**Review by seanjhardy — APPROVED** [review]

**Pull request closed without merging**
