### PR TITLE
store the user account creation date

### PR DESCRIPTION
**Pull request by JamesHoran**

### CODE REVIEW

**Comment by OmerSabic** [comment]
At the top of the file, there is a comment that explains the purpose of each field. Could you add one for the field you added?

**Comment by OmerSabic** [comment]
Congrats on your first PR! Just gotta have Sean approve it now.

**Review by seanjhardy — APPROVED** [review]
Was trying to wrap my head around which parts where new vs not until I just checked your commits individually. No idea why this pr has a load of older commits as well but LGTM

**Comment by seanjhardy** [comment]
wait this is merging into main, is that fine?? @OmerSabic

**Pull request merged**
